version: '3.8'

services:
  db-magazine:
    image: mariadb:11.4
    container_name: sf-magazine-db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=magazine_db
    volumes:
      - sf_magazine_db_data:/var/lib/mysql
    networks:
      - sf-network
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin-magazine:
    image: phpmyadmin:latest
    container_name: sf-magazine-phpmyadmin
    restart: always
    ports:
      - "9001:80" # Mantiene la porta 9001 esterna, phpmyadmin risponde internamente sulla 80
    depends_on:
      db-magazine:
        condition: service_healthy
    environment:
      - PMA_HOST=db-magazine # Sfrutta il DNS interno di Docker per raggiungere MariaDB
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - sf-network

  backend-magazine:
    build: ./server
    container_name: sf-magazine-backend
    restart: always
    ports:
      - "8096:8096" # Espone la porta del backend per ricevere il traffico proxato da Vite
    depends_on:
      db-magazine:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://sf-magazine-db:3306/magazine_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      # Forza Spring Boot a fidarsi degli headers di Nginx per sbloccare il login (errore 403)
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
    networks:
      - sf-network

  frontend-magazine:
    build: ./client
    container_name: sf-magazine-frontend
    restart: always
    ports:
      - "5173:5173" # Espone la porta di Vite per Nginx Proxy Manager
    # Forza Vite ad accettare connessioni esterne al container sulla porta di default (5173)
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_ALLOW_HOSTS=all
    depends_on:
      - backend-magazine
    networks:
      - sf-network

volumes:
  sf_magazine_db_data:

networks:
  sf-network:
    external: true
