spring.application.name=magazine

# Connessione a MAMP - Ho aggiornato il nome del DB a magazine_db
# Usa il nome del servizio nel docker-compose invece di localhost
spring.datasource.url=jdbc:mariadb://db-magazine:3306/magazine_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Istruzioni per Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Questo deve corrispondere al percorso che hai mappato nel volume del container
magazine.upload.dir=/app/uploads

# Questo è l'URL pubblico che TinyMCE chiamerà
magazine.upload.base-url=https://magazine.skillfactory.it/uploads/

# Imposta la dimensione massima del singolo file caricato
spring.servlet.multipart.max-file-size=10MB

# Imposta la dimensione massima totale della richiesta (es. testo + immagini)
spring.servlet.multipart.max-request-size=10MB

server.port=8096